//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorTarefas.ServicoGerenciadorTarefas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tarefa", Namespace="http://schemas.datacontract.org/2004/07/ServicoGerenciadorTarefas.Modelos")]
    [System.SerializableAttribute()]
    public partial class Tarefa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataTarefaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoTarefaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTarefaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TarefaConcluidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataTarefa {
            get {
                return this.DataTarefaField;
            }
            set {
                if ((this.DataTarefaField.Equals(value) != true)) {
                    this.DataTarefaField = value;
                    this.RaisePropertyChanged("DataTarefa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoTarefa {
            get {
                return this.DescricaoTarefaField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoTarefaField, value) != true)) {
                    this.DescricaoTarefaField = value;
                    this.RaisePropertyChanged("DescricaoTarefa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTarefa {
            get {
                return this.IdTarefaField;
            }
            set {
                if ((this.IdTarefaField.Equals(value) != true)) {
                    this.IdTarefaField = value;
                    this.RaisePropertyChanged("IdTarefa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TarefaConcluida {
            get {
                return this.TarefaConcluidaField;
            }
            set {
                if ((this.TarefaConcluidaField.Equals(value) != true)) {
                    this.TarefaConcluidaField = value;
                    this.RaisePropertyChanged("TarefaConcluida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoGerenciadorTarefas.ITarefaService")]
    public interface ITarefaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITarefaService/Add", ReplyAction="http://tempuri.org/ITarefaService/AddResponse")]
        void Add(GerenciadorTarefas.ServicoGerenciadorTarefas.Tarefa tarefa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITarefaService/Add", ReplyAction="http://tempuri.org/ITarefaService/AddResponse")]
        System.Threading.Tasks.Task AddAsync(GerenciadorTarefas.ServicoGerenciadorTarefas.Tarefa tarefa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITarefaService/Finish", ReplyAction="http://tempuri.org/ITarefaService/FinishResponse")]
        void Finish(int idTarefa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITarefaService/Finish", ReplyAction="http://tempuri.org/ITarefaService/FinishResponse")]
        System.Threading.Tasks.Task FinishAsync(int idTarefa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITarefaService/Reopen", ReplyAction="http://tempuri.org/ITarefaService/ReopenResponse")]
        void Reopen(int idTarefa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITarefaService/Reopen", ReplyAction="http://tempuri.org/ITarefaService/ReopenResponse")]
        System.Threading.Tasks.Task ReopenAsync(int idTarefa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITarefaService/GetTarefasAbertas", ReplyAction="http://tempuri.org/ITarefaService/GetTarefasAbertasResponse")]
        GerenciadorTarefas.ServicoGerenciadorTarefas.Tarefa[] GetTarefasAbertas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITarefaService/GetTarefasAbertas", ReplyAction="http://tempuri.org/ITarefaService/GetTarefasAbertasResponse")]
        System.Threading.Tasks.Task<GerenciadorTarefas.ServicoGerenciadorTarefas.Tarefa[]> GetTarefasAbertasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITarefaService/GetTarefasConcluidas", ReplyAction="http://tempuri.org/ITarefaService/GetTarefasConcluidasResponse")]
        GerenciadorTarefas.ServicoGerenciadorTarefas.Tarefa[] GetTarefasConcluidas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITarefaService/GetTarefasConcluidas", ReplyAction="http://tempuri.org/ITarefaService/GetTarefasConcluidasResponse")]
        System.Threading.Tasks.Task<GerenciadorTarefas.ServicoGerenciadorTarefas.Tarefa[]> GetTarefasConcluidasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITarefaServiceChannel : GerenciadorTarefas.ServicoGerenciadorTarefas.ITarefaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TarefaServiceClient : System.ServiceModel.ClientBase<GerenciadorTarefas.ServicoGerenciadorTarefas.ITarefaService>, GerenciadorTarefas.ServicoGerenciadorTarefas.ITarefaService {
        
        public TarefaServiceClient() {
        }
        
        public TarefaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TarefaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TarefaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TarefaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add(GerenciadorTarefas.ServicoGerenciadorTarefas.Tarefa tarefa) {
            base.Channel.Add(tarefa);
        }
        
        public System.Threading.Tasks.Task AddAsync(GerenciadorTarefas.ServicoGerenciadorTarefas.Tarefa tarefa) {
            return base.Channel.AddAsync(tarefa);
        }
        
        public void Finish(int idTarefa) {
            base.Channel.Finish(idTarefa);
        }
        
        public System.Threading.Tasks.Task FinishAsync(int idTarefa) {
            return base.Channel.FinishAsync(idTarefa);
        }
        
        public void Reopen(int idTarefa) {
            base.Channel.Reopen(idTarefa);
        }
        
        public System.Threading.Tasks.Task ReopenAsync(int idTarefa) {
            return base.Channel.ReopenAsync(idTarefa);
        }
        
        public GerenciadorTarefas.ServicoGerenciadorTarefas.Tarefa[] GetTarefasAbertas() {
            return base.Channel.GetTarefasAbertas();
        }
        
        public System.Threading.Tasks.Task<GerenciadorTarefas.ServicoGerenciadorTarefas.Tarefa[]> GetTarefasAbertasAsync() {
            return base.Channel.GetTarefasAbertasAsync();
        }
        
        public GerenciadorTarefas.ServicoGerenciadorTarefas.Tarefa[] GetTarefasConcluidas() {
            return base.Channel.GetTarefasConcluidas();
        }
        
        public System.Threading.Tasks.Task<GerenciadorTarefas.ServicoGerenciadorTarefas.Tarefa[]> GetTarefasConcluidasAsync() {
            return base.Channel.GetTarefasConcluidasAsync();
        }
    }
}
